---
title: "Forschungsvorhaben (Exposé)"
---

Bitte erstellen Sie zunächst eine Übersicht Ihres Forschungsvorhabens. Nutzen Sie dafür die hier bereitgestellte Vorlage und fügen Sie Ihre Antworten direkt unter die Fragen ein.

::: {.callout-tip title="Vorlage"}
[Vorlage Beschreibung Forschungsvorhaben](https://docs.google.com/document/d/1RURkidZvrVMBgtXxJG3D4exw9FBnkmFFSMxkpXMovZ0/edit?usp=sharing)
:::

Senden Sie das ausgefüllte Forschungsvorhaben anschließend als PDF per E-Mail an [kirenz@hdm-stuttgart.de](mailto:kirenz@hdm-stuttgart.de). Bitte beachten Sie dafür die Frist und die Vorgaben unter [Ablauf und Fristen](ablauf.qmd).

## Leitfragen

1. Welchem Themengebiet widmet sich die Arbeit?

1. Welche konkrete Frage soll beantwortet werden?

1. Weshalb ist die Beantwortung der Frage relevant?

1. Welche Art wissenschaftlicher Arbeit wählen Sie (Design Science Research oder quantitativ empirisch)?

1. Welche verallgemeinerbare Erkenntnisse wird die Arbeit voraussichtlich für die Praxis generieren?

1. Welchen Beitrag wird die Arbeit für die wissenschaftliche Theorie leisten?

1. Recherchieren und nennen Sie drei zentrale Quellen, die Sie für die Bearbeitung der Fragestellung als besonders relevant erachten.

1. Listen Sie die Keywords auf, die Sie für die Recherche der Literatur verwendet haben.
